FROM ultralytics/ultralytics:latest

RUN pip install --upgrade pip && \
    pip install \
    ultralytics \
    flask \
    Flask-SocketIO \
    opencv-python \
    torch \
    torchvision \
    torchaudio

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

WORKDIR /app

COPY . .

CMD ["python", "app.py"]