FROM ultralytics/ultralytics:latest

RUN pip install --upgrade pip && \
    pip install \
    ultralytics \
    flask \
    Flask-SocketIO \
    opencv-python

WORKDIR /app

COPY . .

CMD ["python", "app.py"]