services:
  fyp:
    platform: linux/amd64
    image: nvidia/cuda:12.3.6-base-ubuntu20.04 # get the nvidia cuda image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: CW_fyp
    volumes:
      - ./app:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # allow useing nvidia gpu
      - INTEL_VISIBLE_DEVICES=all # allow useing intel gpu
    shm_size: '15gb' # give 15GB RAM 
    ports:
      - 8080:8080
