services:
  fyp:
    platform: linux/amd64
    image: nvidia/cuda:12.3.6-base-ubuntu20.04 # get the nvidia cuda image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: CW_fyp
    volumes:
      - ./app:/app
      - ./client_secret_10875450332-bc8mhv9q2fts2cf5pc1f4akiv55vmpvr.apps.googleusercontent.com.json:/client_secret_10875450332-bc8mhv9q2fts2cf5pc1f4akiv55vmpvr.apps.googleusercontent.com.json
      - ./token.json:/token.json
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # allow useing nvidia gpu
      - INTEL_VISIBLE_DEVICES=all # allow useing intel gpu
    shm_size: '15gb' # give 15GB RAM 
    ports:
      - 8080:8080
