FROM ultralytics/ultralytics:latest

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install \
    ultralytics \
    flask \
    opencv-python \
    Flask-SocketIO \
    tensorflow \
    numpy \
    Flask-Mail \
    flask-cors \
    gdown

CMD ["python3", "app.py"]