FROM ultralytics/ultralytics:latest

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install \
    numpy \
    panda \
    ultralytics \
    flask \
    opencv-python \
    Flask-SocketIO \
    tensorflow \
    Flask-Mail \
    flask-cors \
    gdown \
    google-auth \
    google-auth-oauthlib \
    google-auth-httplib2 \
    google-api-python-client

CMD ["python3", "app.py"]